import { v4 as uuid } from 'uuid';

export const products = [
  {
    id: uuid(),
    createdAt: '27/03/2019',
    media: '/static/images/products/product_1.png',
    vues: '594',
    wilaya: 16,
    realisation_date: new Date(),
    surface: 80,
    rooms: 'F3',
    purchase_method: 'ACHAT DIRECT',
    product_typologie: 'INDIVIDUEL',
    standing: 'ORDINAIRE',
    nearby: [],
    options: [],
  },
  {
    id: uuid(),
    createdAt: '27/03/2019',
    media: '/static/images/products/product_1.png',
    vues: '594',
    wilaya: 16,
    realisation_date: new Date(),
    surface: 80,
    rooms: 'F3',
    purchase_method: 'ACHAT DIRECT',
    product_typologie: 'INDIVIDUEL',
    standing: 'ORDINAIRE',
    nearby: [],
    options: [],
  },
  {
    id: uuid(),
    createdAt: '27/03/2019',
    media: '/static/images/products/product_1.png',
    vues: '594',
    wilaya: 16,
    realisation_date: new Date(),
    surface: 80,
    rooms: 'F3',
    purchase_method: 'ACHAT DIRECT',
    product_typologie: 'INDIVIDUEL',
    standing: 'ORDINAIRE',
    nearby: [],
    options: [],
  },
  {
    id: uuid(),
    createdAt: '27/03/2019',
    media: '/static/images/products/product_1.png',
    vues: '594',
    wilaya: 16,
    realisation_date: new Date(),
    surface: 80,
    rooms: 'F3',
    purchase_method: 'ACHAT DIRECT',
    product_typologie: 'INDIVIDUEL',
    standing: 'ORDINAIRE',
    nearby: [],
    options: [],
  },
];
